source 'https://rubygems.org'

ruby '2.2.2'
gem 'sinatra'
gem 'json'
gem 'mechanize'
gem 'unicorn'
gem 'figaro'

group :production do
  gem 'thin'
end

group :development,:test do
  gem 'byebug'
end

